---
name: HTML-BBReverse
version: 0.03
author:
  - 'Y. Heling, E<lt>yorhel@cpan.orgE<gt>'
abstract: Perl module to convert HTML to BBCode and back
license: perl
provides:
  HTML::BBReverse:
    file: lib/HTML/BBReverse.pm
    version: 0.03
generated_by: Module::Build version 0.2611
